const version="1.0.9"
const CheerpX = await import(`https://cxrtnc.leaningtech.com/${version}/cx.esm.js`);
export const Linux = CheerpX.Linux;
export const HttpBytesDevice = CheerpX.HttpBytesDevice;
export const CloudDevice = CheerpX.CloudDevice;
export const GitHubDevice = CheerpX.GitHubDevice;
export const IDBDevice = CheerpX.IDBDevice;
export const WebDevice = CheerpX.WebDevice;
export const DataDevice = CheerpX.DataDevice;
export const OverlayDevice = CheerpX.OverlayDevice;
export const System = CheerpX.System;
